### ISSUE TITLE
Help-me

### ISSUE THREAD

**Issue by oficialdank2k** [gochendong/suno-api#15]
2024-11-30 18:46:05 suno-api  | Traceback (most recent call last):
2024-11-30 18:46:05 suno-api  |   File "/usr/local/bin/uvicorn", line 8, in <module>
2024-11-30 18:46:05 suno-api  |     sys.exit(main())
2024-11-30 18:46:05 suno-api  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
2024-11-30 18:46:05 suno-api  |     return self.main(*args, **kwargs)
2024-11-30 18:46:05 suno-api  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
2024-11-30 18:46:05 suno-api  |     rv = self.invoke(ctx)
2024-11-30 18:46:05 suno-api  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
2024-11-30 18:46:05 suno-api  |     return ctx.invoke(self.callback, **ctx.params)
2024-11-30 18:46:05 suno-api  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
2024-11-30 18:46:05 suno-api  |     return __callback(*args, **kwargs)
2024-11-30 18:46:05 suno-api  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 412, in main
2024-11-30 18:46:05 suno-api  |     run(
2024-11-30 18:46:05 suno-api  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
2024-11-30 18:46:05 suno-api  |     server.run()
2024-11-30 18:46:05 suno-api  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
2024-11-30 18:46:05 suno-api  |     return asyncio.run(self.serve(sockets=sockets))
2024-11-30 18:46:05 suno-api  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
2024-11-30 18:46:05 suno-api  |     return loop.run_until_complete(main)
2024-11-30 18:46:05 suno-api  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
2024-11-30 18:46:05 suno-api  |     return future.result()
2024-11-30 18:46:05 suno-api  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
2024-11-30 18:46:05 suno-api  |     await self._serve(sockets)
2024-11-30 18:46:05 suno-api  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
2024-11-30 18:46:05 suno-api  |     config.load()
2024-11-30 18:46:05 suno-api  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
2024-11-30 18:46:05 suno-api  |     self.loaded_app = import_from_string(self.app)
2024-11-30 18:46:05 suno-api  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
2024-11-30 18:46:05 suno-api  |     module = importlib.import_module(module_str)
2024-11-30 18:46:05 suno-api  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2024-11-30 18:46:05 suno-api  |     return _bootstrap._gcd_import(name[level:], package, level)
2024-11-30 18:46:05 suno-api  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2024-11-30 18:46:05 suno-api  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2024-11-30 18:46:05 suno-api  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2024-11-30 18:46:05 suno-api  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2024-11-30 18:46:05 suno-api  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-11-30 18:46:05 suno-api  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-11-30 18:46:05 suno-api  |   File "/app/main.py", line 5, in <module>
2024-11-30 18:46:05 suno-api  |     from deps import get_token
2024-11-30 18:46:05 suno-api  |   File "/app/deps.py", line 1, in <module>
2024-11-30 18:46:05 suno-api  |     from cookie import suno_auth, keep_alive
2024-11-30 18:46:05 suno-api  |   File "/app/cookie.py", line 97, in <module>
2024-11-30 18:46:05 suno-api  |     fetch_session_id(suno_auth)
2024-11-30 18:46:05 suno-api  |   File "/app/cookie.py", line 75, in fetch_session_id
2024-11-30 18:46:05 suno-api  |     expire_at = resp.json().get("response").get("sessions")[0]["expire_at"]
2024-11-30 18:46:05 suno-api  | IndexError: list index out of range
2024-11-30 18:46:22 suno-api  | Traceback (most recent call last):
2024-11-30 18:46:22 suno-api  |   File "/usr/local/bin/uvicorn", line 8, in <module>
2024-11-30 18:46:22 suno-api  |     sys.exit(main())
2024-11-30 18:46:22 suno-api  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
2024-11-30 18:46:22 suno-api  |     return self.main(*args, **kwargs)
2024-11-30 18:46:22 suno-api  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
2024-11-30 18:46:22 suno-api  |     rv = self.invoke(ctx)
2024-11-30 18:46:22 suno-api  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
2024-11-30 18:46:22 suno-api  |     return ctx.invoke(self.callback, **ctx.params)
2024-11-30 18:46:22 suno-api  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
2024-11-30 18:46:22 suno-api  |     return __callback(*args, **kwargs)
2024-11-30 18:46:22 suno-api  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 412, in main
2024-11-30 18:46:22 suno-api  |     run(
2024-11-30 18:46:22 suno-api  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
2024-11-30 18:46:22 suno-api  |     server.run()
2024-11-30 18:46:22 suno-api  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
2024-11-30 18:46:22 suno-api  |     return asyncio.run(self.serve(sockets=sockets))
2024-11-30 18:46:22 suno-api  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
2024-11-30 18:46:22 suno-api  |     return loop.run_until_complete(main)
2024-11-30 18:46:22 suno-api  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
2024-11-30 18:46:22 suno-api  |     return future.result()
2024-11-30 18:46:22 suno-api  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
2024-11-30 18:46:22 suno-api  |     await self._serve(sockets)
2024-11-30 18:46:22 suno-api  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
2024-11-30 18:46:22 suno-api  |     config.load()
2024-11-30 18:46:22 suno-api  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
2024-11-30 18:46:22 suno-api  |     self.loaded_app = import_from_string(self.app)
2024-11-30 18:46:22 suno-api  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
2024-11-30 18:46:22 suno-api  |     module = importlib.import_module(module_str)
2024-11-30 18:46:22 suno-api  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2024-11-30 18:46:22 suno-api  |     return _bootstrap._gcd_import(name[level:], package, level)
2024-11-30 18:46:22 suno-api  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2024-11-30 18:46:22 suno-api  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2024-11-30 18:46:22 suno-api  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2024-11-30 18:46:22 suno-api  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2024-11-30 18:46:22 suno-api  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-11-30 18:46:22 suno-api  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-11-30 18:46:22 suno-api  |   File "/app/main.py", line 5, in <module>
2024-11-30 18:46:22 suno-api  |     from deps import get_token
2024-11-30 18:46:22 suno-api  |   File "/app/deps.py", line 1, in <module>
2024-11-30 18:46:22 suno-api  |     from cookie import suno_auth, keep_alive
2024-11-30 18:46:22 suno-api  |   File "/app/cookie.py", line 97, in <module>
2024-11-30 18:46:22 suno-api  |     fetch_session_id(suno_auth)
2024-11-30 18:46:22 suno-api  |   File "/app/cookie.py", line 75, in fetch_session_id
2024-11-30 18:46:22 suno-api  |     expire_at = resp.json().get("response").get("sessions")[0]["expire_at"]
2024-11-30 18:46:22 suno-api  | IndexError: list index out of range
2036-01-01 00:00:00

dont work

**Comment by gochendong** [comment]
use correct cookie according to README

**Comment by pranky89** [comment]
make sure you are not using quotes for cookie in your .env file.
